### ISSUE TITLE
The severity (level) has not been reflected

### ISSUE THREAD

**Issue by MasayaTahara** [hunt3rkillerz/Snyk-To-Sarif-JS#2]
Thank you for creating this tool. I think the severity (level) for each detection item is missing in the SARIF file. It is written in vulnerabilities/severity in the Snyk original json format and should be written in runs/results/level in SARIF format. You can use the following command to compare.
```sh
snyk test --docker alpine:3.11.11 --json
snyk test --docker alpine:3.11.11 --json | snyk-to-sarif
```

**Comment by hunt3rkillerz** [comment]
Hi @MasayaTahara, thank you for raising this issue and sorry I missed this one (I didn't get the notification for some reason)! I believe this is a new addition to the SARIF standard. More than happy to add in this functionality. However, I wanted to first ask if you'd be keen to attempt a fork & PR (no pressure, just wanted to extend the opportunity).

All the best and glad the tool has helped you so far!

**Comment by MasayaTahara** [comment]
@hunt3rkillerz Thank you for your comments. I will try to handle this issue. By the way, is the following mapping for severity and level OK?

| Severity (Snyk) | Level (SARIF) |
| -- | -- |
| Low | note |
| Medium | warning |
| High | warning |
| Critical | error |

Refer the link below:
- https://support.snyk.io/hc/en-us/articles/4403987394961-Severity-levels
- https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json

**Comment by hunt3rkillerz** [comment]
That seems reasonable, I'd consider making High an Error though based on the relative risk those kinds of issues may present.
